# build stage
FROM node:10-jessie as build-stage

WORKDIR /app

RUN apt-get update
RUN apt-get install -y apt-transport-https
RUN curl -o- -L https://yarnpkg.com/install.sh | bash

COPY package.json yarn.lock ./

RUN yarn install
COPY . .
RUN yarn build

# production stage
FROM nginx:1.15-alpine as production-stage
COPY --from=build-stage /app/dist /usr/share/nginx/html
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
